version: '3.3'
services:
    postgres:
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_PASSWORD=haola123
        container_name: pg
        image: 'postgres:latest'